id = "short-giraffe-theme"
name = "Short Giraffe Theme"
version = "2.2.1"
schema_version = 1
authors = ["kumamaki <8641684+kumamaki@users.noreply.github.com>"]
description = "A dark theme with carefully picked colors"
repository = "https://github.com/kumamaki/Short-Giraffe"
